### ISSUE TITLE
CTL 470 not working :( Please Help! 

### ISSUE THREAD

**Issue by milapraschma** [thenickdude/wacom-driver-fix#44]
Firstly, I wasn't sure whether we were supposed to uninstall the original Wacom Driver so I did that anyway - should I reinstall it and begin the process again?

Everything looks good and my tablet comes up under the Wacom app in System Preferences - however, it won't work. Trying to paint in PhotoShop and the curser isn't moving. [Had to use the Terminal app to input the commands to give permissions for the tablet. Touching my stylus to the screen didn't prompt the access pop-up.]

I have the CTL-470 Bamboo Pen tablet, and the Intuos LP-190k Stylus. My friend uses this combination on her PC and it worked fine for her. Any suggestions? I have attached screenshots.
 
![Screenshot 2020-10-17 at 13 36 36](https://user-images.githubusercontent.com/73024358/96337282-d971c380-107d-11eb-84f6-18cb534052f8.png)

![Screenshot 2020-10-17 at 13 36 46](https://user-images.githubusercontent.com/73024358/96337284-daa2f080-107d-11eb-8bcf-d0929dd1d678.png)

![Screenshot 2020-10-17 at 13 31 11](https://user-images.githubusercontent.com/73024358/96337197-083b6a00-107d-11eb-89f4-b26a9e0015ba.png)

![Screenshot 2020-10-17 at 13 31 57](https://user-images.githubusercontent.com/73024358/96337208-230dde80-107d-11eb-84bc-a97b17a66b91.png)

**Comment by thenickdude** [comment]
It's fine to uninstall the Wacom driver before installing my driver, but you don't need to.

It looks like the driver is fully functional, so all it is missing is the Accessibility permission it needs to move your mouse cursor around. If it already appears in the Accessibility list, use the minus button to remove it and reboot your computer, then re-tick the entry that reappears for you, this should fix it.

If it doesn't appear in the list, go to the directory "/Library/Application Support/Tablet/" in the finder (using Go -> Go to Folder) and drag and drop the PenTabletDriver file you see there into the Accessibility list instead, then reboot your computer if the tablet doesn't start working immediately.

**Comment by milapraschma** [comment]
Hmm, still no luck! What can I send through to help? Thank you BTW!

**Comment by thenickdude** [comment]
Try holding the Alt key on your keyboard and click the About button that's visible in the bottom right corner of your last screenshot, this will open up a debugging window.

See if it looks like it can detect the pressure and X Y coordinates changing as you use your pen.

**Comment by milapraschma** [comment]
![Screenshot 2020-10-30 at 12 26 07](https://user-images.githubusercontent.com/73024358/97704891-18a30a00-1aab-11eb-801a-24e174aedf1d.png)

**Comment by thenickdude** [comment]
The stylus you're using isn't listed as being compatible with that tablet:

https://machollywood.com/blogs/news/wacom-pen-compatibility

Are you sure that's the combo your friend is using?

**Comment by thenickdude** [comment]
Do those numbers in the right column change as you use your pen or not?

**Comment by milapraschma** [comment]
Ahh I will double check with her, but no those numbers do not change whatsoever. :(

**Comment by milapraschma** [comment]
I am assuming there isn't a way to fix this particular issue short of finding a compatible pen?

**Comment by thenickdude** [comment]
If the pen is incompatible this is certainly the symptoms you'd get from it.

Does the LED on the tablet light up brighter when you tap the pen on it?

**Comment by milapraschma** [comment]
I am afraid not. I will see if I can find a compatible pen, otherwise I'm assuming this renders my tablet useless?

**Comment by thenickdude** [comment]
Right, only specific pen models are compatible, and the others can't be made to work.

**Comment by milapraschma** [comment]
Alright, well thank you so much for your help!
